project:
  type: website
  output-dir: docs

website:
  title: " "
  navbar:
    left:
      - href: index.qmd
        text: Home
      - icon: person-raised-hand
        text: About
        href: about.qmd
      - icon: book
        text: Research
        href: research.qmd
      - icon: file-person
        text: CV
        href: CV/index.qmd
      - icon: book
        text: Publications
        href: publications.qmd
      - icon: pencil
        text: Teaching
        href: teaching.qmd

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: true

editor: visual

