---
title: "Research"
---

My work is about with how people acquire and discard habits and beliefs across the life-course, and how these individual-level processes aggregate up to large-scale patterns of cultural change. I have developed this research agenda against the backdrop of a burgeoning interdisciplinary interest in how individuals acquire, internalize, and transmit culture.

## Personal culture (and its development)

A key part of my work is how we measure internalized culture. To understand how people change their attitudes, we need first to understand what we are measuring. Some of my work seeks tools to accomplish this. I have used semantic differentials to measure the [connotative meanings of moral dilemmas](https://doi.org/10.1016/j.poetic.2021.101643) and [rugged landscapes](https://osf.io/preprints/socarxiv/wdh3f) to represent attitudinal spaces and to examine how individuals move across them. I have also built [intrapersonal identity networks](https://osf.io/preprints/socarxiv/fahe3/), showing that the structure of relationships between identities within the self is associated with key well-being outcomes.

## Openness to change

A second component of my research investigates the contexts in which individuals are open to changing their minds based on novel information. Recent work on attitudinal development has regularly found that, after a certain age, individuals rarely change their beliefs. This finding resonates with work on formative periods from other disciplines. This leads to several questions. First, we wonder whether this pattern of early exploration followed by stability is robust across cultures. In a project with [Kevin Kiley](https://krkiley.github.io/), we explore whether these formative windows have changed given the dramatic changes in the timing of life-course transitions over the past 50 years. A formative period early in the life course also suggests that most change should occur through cohort replacement. In this [paper](https://www.cambridge.org/core/journals/evolutionary-human-sciences/article/opinions-on-hardtodiscuss-topics-change-more-via-cohort-replacement/D11EC23A36D627465FDC9AA52AD049E1), we examine the relative contribution of cohort-replacement and individual-level change in accounting for patterns of cultural variation across several countries over the past 40 years. We find some initial evidence that certain cultural issues might change via different mechanisms. Relatedly, [here](https://osf.io/preprints/socarxiv/y8b2e), I explore the implications of variations in the length and shape of formative periods for understanding the pace at which cohort replacement occurs. Through an agent-based simulation, I show that the interplay between the length of formative periods and the demographic makeup of a population affects rates of cultural change.

## Cultural Transmission

A third theme in my work is related to how culture is transmitted via social networks. I integrate sociological work on social influence with ongoing behavioral science research about social learning. There are many parallels between these strands of work that remain unexploited. [Here](https://osf.io/preprints/socarxiv/2vyhp/), a colleague and I show that different social learning strategies combine with the topology of networks to produce different patterns of cultural diffusion. This paper builds on my previous work that examined what kind of networks are better suited for efficient cultural transmission. In interdisciplinary work with different teams, we have shown that central-place foraging – characteristic of hunter-gatherers – results in [efficient networks for cultural diffusion](https://royalsocietypublishing.org/doi/full/10.1098/rsos.211324), and we have examined how resilient animal networks are to the removal of particular nodes, simulating the effects of poaching.

## Current Work

My post-doctoral work brings these three themes together. We are studying a new pilgrimage site in Peru to understand how collective rituals emerge and become institutionalized. This requires understanding how to conceptualize and measure the adoption of a new belief. In our fieldwork, we are using traditional survey questions, as well as economic games and cognitive tasks. A key part for understanding this puzzle is figuring out who the first adopters are. This, in turn, will shed light on ongoing theorizing about the circumstances that make individuals more open to adopting new beliefs. Further, we need to understand the social networks through which information about the existence of the site – and its miracle-granting powers -- is transmitted.
